In [1981]:
import numpy as np 
import pandas as pd 
import os
import pyodbc
from sqlalchemy import create_engine
from urllib.parse import quote_plus

### `Creating Series`

In [1982]:
ser_1 = pd.Series([1, 2, 3, 4, 5])
print(ser_1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

- **Series with Custom Index**

In [1983]:
ages = pd.Series(
    [23, 22, 20],
    index=["Khaled", "Ali", "Sameh"]
)

print(ages)

Khaled    23
Ali       22
Sameh     20
dtype: int64

In [1984]:
users = pd.Series(
    [23, 22, 20],
    index=["Khaled", "Ali", "Sameh"],
    name="Ages",
    dtype=np.int64
)
print(users)

Khaled    23
Ali       22
Sameh     20
Name: Ages, dtype: int64

- *Access an element*

In [1985]:
ser_2 = pd.Series(
    ['a', 'b', 'c', 'd', 'e']
)

print(ser_2[0])
print(ser_2[4])

a
e

- *slicing*

In [1986]:
ser_2 = pd.Series(
    ['a', 'b', 'c', 'd', 'e']
)

print(ser_2[0:4])
print('-' * 20)
print(ser_2[:4])
print('-' * 20)
print(ser_2[1:])
print('-' * 20)
print(ser_2[::2])
print('-' * 20)
print(ser_2[::-1])

0    a
1    b
2    c
3    d
dtype: object
--------------------
0    a
1    b
2    c
3    d
dtype: object
--------------------
1    b
2    c
3    d
4    e
dtype: object
--------------------
0    a
2    c
4    e
dtype: object
--------------------
4    e
3    d
2    c
1    b
0    a
dtype: object

- *check the shape*

In [1987]:
ser_2.shape

(5,)

- *check total elements*

In [1988]:
ser_2.size

5

- *check the unique values*

In [1989]:
ser_2.unique

<bound method Series.unique of 0    a
1    b
2    c
3    d
4    e
dtype: object>

In [1990]:
print(ser_2.unique())

['a' 'b' 'c' 'd' 'e']

- *total unique values*

In [1991]:
print(ser_2.nunique())

5

- *total number of elements*

In [1992]:
print(len(ser_2))

5

#### `in`
- **check the index not a value**

In [1993]:
ser3 = pd.Series(
    ["ali", "ahmed", "alaa", "khaled"]
)
ser3

0       ali
1     ahmed
2      alaa
3    khaled
dtype: object

In [1994]:
print("ali" in ser3)

False

In [1995]:
print("ali" not in ser3)

True

In [1996]:
print(0 in ser3)
print(100 in ser3)

True
False

##### `getting all index`
##### `getting all values`

In [1997]:
print(ser3.index)

RangeIndex(start=0, stop=4, step=1)

In [1998]:
print(ser3.values)

['ali' 'ahmed' 'alaa' 'khaled']

In [1999]:
print("ali" in ser3.values)

True

#### `Creating a DataFrame`

In [2000]:
row1 = ['khaled', 'AI', 23000]
row2 = ['Ali', 'Data Science', 25000]
row3 = ['Sameh', 'Web Development', 20000]
row4 = ['Ahmed', 'Data Analysis', 30000]

df = pd.DataFrame(
    [row1, row2, row3, row4],
    index=[1, 2, 3, 4],
    columns=['Name', 'Course', 'Salary']
)
df

     Name           Course  Salary
1  khaled               AI   23000
2     Ali     Data Science   25000
3   Sameh  Web Development   20000
4   Ahmed    Data Analysis   30000

In [2001]:
data = {
    "name": ["Khaled", "Ali", "Sameh", "Samy", "Omar", "Ahmed", "Mohamed", "Hossam", "Youssef", "Tamer"],
    "age": [23, 22, 20, 25, 24, 26, 21, 27, 22, 28],
    "department": ["ML", "Data Analyst", "HR", "ML", "HR", "Data Scientist", "Marketing", "Sales", "Finance", "Operations"],
    "salary": [100000, 18000, 30000, 75000, 25000, 80000, 45000, 55000, 65000, 70000]
}

df_data = pd.DataFrame(data)

df_data

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

- *get the index*

In [2002]:
df_data.index

RangeIndex(start=0, stop=10, step=1)

- *get column names*

In [2003]:
df_data.columns

Index(['name', 'age', 'department', 'salary'], dtype='object')

- *get values*

In [2004]:
df_data.values

array([['Khaled', 23, 'ML', 100000],
       ['Ali', 22, 'Data Analyst', 18000],
       ['Sameh', 20, 'HR', 30000],
       ['Samy', 25, 'ML', 75000],
       ['Omar', 24, 'HR', 25000],
       ['Ahmed', 26, 'Data Scientist', 80000],
       ['Mohamed', 21, 'Marketing', 45000],
       ['Hossam', 27, 'Sales', 55000],
       ['Youssef', 22, 'Finance', 65000],
       ['Tamer', 28, 'Operations', 70000]], dtype=object)

- *shape*

In [2005]:
df_data.shape

(10, 4)

- *total number of rows*

In [2006]:
len(df_data)

10

In [2007]:
print(f"Number of rows: {df_data.shape[0]}")
print(f"Number of columns: {df_data.shape[1]}")

Number of rows: 10
Number of columns: 4

##### **`Inspect the Data`**

In [2008]:
df_data

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

- **head(n)** || **tail(n)** || **sample(n)**

In [2009]:
df_data.head()

     name  age    department  salary
0  Khaled   23            ML  100000
1     Ali   22  Data Analyst   18000
2   Sameh   20            HR   30000
3    Samy   25            ML   75000
4    Omar   24            HR   25000

In [2010]:
df_data.head(7)

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000

In [2011]:
df_data.tail()

      name  age      department  salary
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

In [2012]:
df_data.tail(7)

      name  age      department  salary
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

In [2013]:
df_data.sample()

   name  age department  salary
4  Omar   24         HR   25000

In [2014]:
df_data.sample(4)

      name  age      department  salary
8  Youssef   22         Finance   65000
5    Ahmed   26  Data Scientist   80000
4     Omar   24              HR   25000
3     Samy   25              ML   75000

##### **`Getting info`**

In [2015]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        10 non-null     object
 1   age         10 non-null     int64
 2   department  10 non-null     object
 3   salary      10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

##### **`describe`**

In [2016]:
df_data.describe()

            age         salary
count  10.00000      10.000000
mean   23.80000   56300.000000
std     2.65832   26566.687578
min    20.00000   18000.000000
25%    22.00000   33750.000000
50%    23.50000   60000.000000
75%    25.75000   73750.000000
max    28.00000  100000.000000

In [2017]:
df_data['department'].describe()

count     10
unique     8
top       ML
freq       2
Name: department, dtype: object

In [2018]:
df_data.describe(include='all')

          name       age department         salary
count       10  10.00000         10      10.000000
unique      10       NaN          8            NaN
top     Khaled       NaN         ML            NaN
freq         1       NaN          2            NaN
mean       NaN  23.80000        NaN   56300.000000
std        NaN   2.65832        NaN   26566.687578
min        NaN  20.00000        NaN   18000.000000
25%        NaN  22.00000        NaN   33750.000000
50%        NaN  23.50000        NaN   60000.000000
75%        NaN  25.75000        NaN   73750.000000
max        NaN  28.00000        NaN  100000.000000

- **Selecting One Column**

In [2019]:
df_data.age

0    23
1    22
2    20
3    25
4    24
5    26
6    21
7    27
8    22
9    28
Name: age, dtype: int64

In [2020]:
df_data['age'] #! best practice to use the column name in brackets when accessing a column in a DataFrame

0    23
1    22
2    20
3    25
4    24
5    26
6    21
7    27
8    22
9    28
Name: age, dtype: int64

In [2021]:
df_data[['name','salary']]

      name  salary
0   Khaled  100000
1      Ali   18000
2    Sameh   30000
3     Samy   75000
4     Omar   25000
5    Ahmed   80000
6  Mohamed   45000
7   Hossam   55000
8  Youssef   65000
9    Tamer   70000

- **`Note That`**
    - *df[column_name]* is `series`
    - *df[[column_name]]* is `Dataframe`

#### **`loc[rows (index),columns (name)]`**
#### **`iloc[rows (index), columns (index)]`**

In [2022]:
df_data

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

- **loc**

In [2023]:
df_data.loc[0] #! get the first row of the DataFrame using the index label 0

name          Khaled
age               23
department        ML
salary        100000
Name: 0, dtype: object

In [2024]:
df_data.loc[0:3] #! get the first four rows of the DataFrame using the index labels 0 to 3

     name  age    department  salary
0  Khaled   23            ML  100000
1     Ali   22  Data Analyst   18000
2   Sameh   20            HR   30000
3    Samy   25            ML   75000

In [2025]:
df_data.loc[0:3,'name'] #! get the first 4 names

0    Khaled
1       Ali
2     Sameh
3      Samy
Name: name, dtype: object

In [2026]:
df_data.loc[::2, ['name', 'department']]

      name department
0   Khaled         ML
2    Sameh         HR
4     Omar         HR
6  Mohamed  Marketing
8  Youssef    Finance

In [2027]:
df_data.loc[::2, 'name': 'salary':2]

      name department
0   Khaled         ML
2    Sameh         HR
4     Omar         HR
6  Mohamed  Marketing
8  Youssef    Finance

- **iloc**

In [2028]:
df_data.iloc[5]

name                   Ahmed
age                       26
department    Data Scientist
salary                 80000
Name: 5, dtype: object

In [2029]:
df_data.iloc[2:7]

      name  age      department  salary
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000

In [2030]:
df_data.iloc[::2,::2]

      name department
0   Khaled         ML
2    Sameh         HR
4     Omar         HR
6  Mohamed  Marketing
8  Youssef    Finance

In [2031]:
df_data.iloc[0,1]

23

#### `Filtering Data`

In [2032]:
df_data.head()

     name  age    department  salary
0  Khaled   23            ML  100000
1     Ali   22  Data Analyst   18000
2   Sameh   20            HR   30000
3    Samy   25            ML   75000
4    Omar   24            HR   25000

In [2033]:
df_data[df_data['age']<=21]

      name  age department  salary
2    Sameh   20         HR   30000
6  Mohamed   21  Marketing   45000

In [2034]:
df_data[df_data["age"] > 22]

     name  age      department  salary
0  Khaled   23              ML  100000
3    Samy   25              ML   75000
4    Omar   24              HR   25000
5   Ahmed   26  Data Scientist   80000
7  Hossam   27           Sales   55000
9   Tamer   28      Operations   70000

#### **`Filtring using Multiple Conditions`**

- **&** `and`
- **|** `or`
- **~** `not`

In [2035]:
df_data[(df_data["age"] > 22) & (df_data["salary"] > 50000)]

     name  age      department  salary
0  Khaled   23              ML  100000
3    Samy   25              ML   75000
5   Ahmed   26  Data Scientist   80000
7  Hossam   27           Sales   55000
9   Tamer   28      Operations   70000

In [2036]:
df_data[(df_data["age"] > 22) | (df_data["salary"] > 50000)]

      name  age      department  salary
0   Khaled   23              ML  100000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

In [2037]:
df_data[(df_data["age"] > 22) & ~(df_data["salary"] > 50000)]

   name  age department  salary
4  Omar   24         HR   25000

##### `isin()`

In [2038]:
df_data[df_data['department'].isin(('ML', 'HR'))]

     name  age department  salary
0  Khaled   23         ML  100000
2   Sameh   20         HR   30000
3    Samy   25         ML   75000
4    Omar   24         HR   25000

#### `Searching Text`

- **contains()**

In [2039]:
df_data[df_data['name'].str.contains('a', case=False)]

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
9    Tamer   28      Operations   70000

In [2040]:
df_data[df_data['name'].str.contains('a', case=True)]

      name  age  department  salary
0   Khaled   23          ML  100000
2    Sameh   20          HR   30000
3     Samy   25          ML   75000
4     Omar   24          HR   25000
6  Mohamed   21   Marketing   45000
7   Hossam   27       Sales   55000
9    Tamer   28  Operations   70000

- **startswith()**

In [2041]:
df_data[df_data['name'].str.startswith('A')]

    name  age      department  salary
1    Ali   22    Data Analyst   18000
5  Ahmed   26  Data Scientist   80000

In [2042]:
df_data[df_data['name'].str.endswith('y')]

   name  age department  salary
3  Samy   25         ML   75000

##### `Sorting Data`

- *sort_values()*

In [2043]:
df_data

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

In [2044]:
df_data.sort_values(by='age', ascending=True)

      name  age      department  salary
2    Sameh   20              HR   30000
6  Mohamed   21       Marketing   45000
1      Ali   22    Data Analyst   18000
8  Youssef   22         Finance   65000
0   Khaled   23              ML  100000
4     Omar   24              HR   25000
3     Samy   25              ML   75000
5    Ahmed   26  Data Scientist   80000
7   Hossam   27           Sales   55000
9    Tamer   28      Operations   70000

In [2045]:
df_data.sort_values(by=['age', 'salary'], ascending=[True, False])

      name  age      department  salary
2    Sameh   20              HR   30000
6  Mohamed   21       Marketing   45000
8  Youssef   22         Finance   65000
1      Ali   22    Data Analyst   18000
0   Khaled   23              ML  100000
4     Omar   24              HR   25000
3     Samy   25              ML   75000
5    Ahmed   26  Data Scientist   80000
7   Hossam   27           Sales   55000
9    Tamer   28      Operations   70000

#### `Creating a New Column`

In [2046]:
df_data["salary_after_bonus"] = df_data["salary"] * 1.10

In [2047]:
df_data

      name  age      department  salary  salary_after_bonus
0   Khaled   23              ML  100000            110000.0
1      Ali   22    Data Analyst   18000             19800.0
2    Sameh   20              HR   30000             33000.0
3     Samy   25              ML   75000             82500.0
4     Omar   24              HR   25000             27500.0
5    Ahmed   26  Data Scientist   80000             88000.0
6  Mohamed   21       Marketing   45000             49500.0
7   Hossam   27           Sales   55000             60500.0
8  Youssef   22         Finance   65000             71500.0
9    Tamer   28      Operations   70000             77000.0

##### `Modifying a Column`

In [2048]:
df_data["salary"] = df_data["salary"] * 1.05

In [2049]:
df_data['salary_level'] = 'low'

df_data.loc[df_data['salary'] > 50000, 'salary_level'] = 'High'

In [2050]:
df_data

      name  age      department    salary  salary_after_bonus salary_level
0   Khaled   23              ML  105000.0            110000.0         High
1      Ali   22    Data Analyst   18900.0             19800.0          low
2    Sameh   20              HR   31500.0             33000.0          low
3     Samy   25              ML   78750.0             82500.0         High
4     Omar   24              HR   26250.0             27500.0          low
5    Ahmed   26  Data Scientist   84000.0             88000.0         High
6  Mohamed   21       Marketing   47250.0             49500.0          low
7   Hossam   27           Sales   57750.0             60500.0         High
8  Youssef   22         Finance   68250.0             71500.0         High
9    Tamer   28      Operations   73500.0             77000.0         High

- *You can use NumPy too*

In [2051]:
df_data2 = df_data.copy()
df_data2.drop(columns=['salary_level'], inplace=True)
df_data2.head()

     name  age    department    salary  salary_after_bonus
0  Khaled   23            ML  105000.0            110000.0
1     Ali   22  Data Analyst   18900.0             19800.0
2   Sameh   20            HR   31500.0             33000.0
3    Samy   25            ML   78750.0             82500.0
4    Omar   24            HR   26250.0             27500.0

In [2052]:
df_data2['salary_level'] = np.where(
    df_data2['salary'] > 50000,
    "High",
    "Low"
)

In [2053]:
df_data2

      name  age      department    salary  salary_after_bonus salary_level
0   Khaled   23              ML  105000.0            110000.0         High
1      Ali   22    Data Analyst   18900.0             19800.0          Low
2    Sameh   20              HR   31500.0             33000.0          Low
3     Samy   25              ML   78750.0             82500.0         High
4     Omar   24              HR   26250.0             27500.0          Low
5    Ahmed   26  Data Scientist   84000.0             88000.0         High
6  Mohamed   21       Marketing   47250.0             49500.0          Low
7   Hossam   27           Sales   57750.0             60500.0         High
8  Youssef   22         Finance   68250.0             71500.0         High
9    Tamer   28      Operations   73500.0             77000.0         High

#### `Some Functions for index`

In [2054]:
data = {
    "name": ["Khaled", "Ali", "Sameh", "Samy", "Omar", "Ahmed", "Mohamed", "Hossam", "Youssef", "Tamer"],
    "age": [23, 22, 20, 25, 24, 26, 21, 27, 22, 28],
    "department": ["ML", "Data Analyst", "HR", "ML", "HR", "Data Scientist", "Marketing", "Sales", "Finance", "Operations"],
    "salary": [100000, 18000, 30000, 75000, 25000, 80000, 45000, 55000, 65000, 70000]
}

df1 = pd.DataFrame(data)

df1

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

- *isin()*

In [2055]:
df1.index.isin([0,2])

array([ True, False,  True, False, False, False, False, False, False,
       False])

In [2056]:
df1[df1.index.isin([0,2])]

     name  age department  salary
0  Khaled   23         ML  100000
2   Sameh   20         HR   30000

- *difference*

In [2057]:
df1.index.difference([0,1])

Index([2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

- *intersection*

In [2058]:
df1.index.intersection([1, 2, 5])

Index([1, 2, 5], dtype='int64')

- *union*

In [2059]:
df1.index.union([3, 4])

RangeIndex(start=0, stop=10, step=1)

- *is_unique*

In [2060]:
df1.index.is_unique

True

- *unique*

In [2061]:
df1.index.unique()

RangeIndex(start=0, stop=10, step=1)

- *delete*

In [2062]:
df1.index.delete(1)

Index([0, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [2063]:
df1

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

- *drop*

In [2064]:
df1.index.drop([1])

Index([0, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [2065]:
df1

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

- *insert*

In [2066]:
df1.index.insert(1,10)

c:\Users\Khaled\anaconda3\Lib\site-packages\IPython\core\displayhook.py:281: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

Index([0, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [2067]:
df1

      name  age      department  salary
0   Khaled   23              ML  100000
1      Ali   22    Data Analyst   18000
2    Sameh   20              HR   30000
3     Samy   25              ML   75000
4     Omar   24              HR   25000
5    Ahmed   26  Data Scientist   80000
6  Mohamed   21       Marketing   45000
7   Hossam   27           Sales   55000
8  Youssef   22         Finance   65000
9    Tamer   28      Operations   70000

- *append*

In [2068]:
df1.index.append(pd.Index([10, 11]))

Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], dtype='int64')

- *is_monotonic_increasing* & *is_monotonic_decreasing*

In [2069]:
df1.index.is_monotonic_increasing

True

In [2070]:
df1.index.is_monotonic_decreasing

False

##### `Missing Values`

In [2071]:
info = {
    "name" : ["Ahmed", "ali", "nour", "sameh"],
    "age": [20,np.nan,25,30],
    "salary":[18000, np.nan, 30000, 40000],
    "department":[np.nan, "AI", "Data Analysis", "Cyber Security"]
}

employees_info = pd.DataFrame(info)
employees_info.head()

    name   age   salary      department
0  Ahmed  20.0  18000.0             NaN
1    ali   NaN      NaN              AI
2   nour  25.0  30000.0   Data Analysis
3  sameh  30.0  40000.0  Cyber Security

In [2072]:
employees_info.isnull().sum()

name          0
age           1
salary        1
department    1
dtype: int64

In [2073]:
employees_info.isna().sum()

name          0
age           1
salary        1
department    1
dtype: int64

#### `drop nulls`

In [2074]:
df_employees_copy1 = employees_info.copy()

In [2075]:
df_employees_copy1.isna().sum()

name          0
age           1
salary        1
department    1
dtype: int64

In [2076]:
df_employees_copy1.dropna(inplace=True)

In [2077]:
df_employees_copy1.isna().sum()

name          0
age           0
salary        0
department    0
dtype: int64

### `fill nulls`

- **fillna()**

In [2078]:
df_employees_copy2 = employees_info.copy()

In [2079]:
df_employees_copy2.isnull().sum()

name          0
age           1
salary        1
department    1
dtype: int64

- *static value*

In [2080]:
df_employees_copy2['department'].fillna("Unknown", inplace=True)
df_employees_copy2.isna().sum()

C:\Users\Khaled\AppData\Local\Temp\ipykernel_8960\1511639018.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_employees_copy2['department'].fillna("Unknown", inplace=True)

name          0
age           1
salary        1
department    0
dtype: int64

- *fill wih mean, median, mode*

In [2081]:
df_employees_copy2['age'].fillna(np.round(df_employees_copy2['age'].mean()), inplace= True)

C:\Users\Khaled\AppData\Local\Temp\ipykernel_8960\1160454435.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_employees_copy2['age'].fillna(np.round(df_employees_copy2['age'].mean()), inplace= True)

In [2082]:
df_employees_copy2.isna().sum()

name          0
age           0
salary        1
department    0
dtype: int64

In [2083]:
df_employees_copy2['salary'].fillna(df_employees_copy2['salary'].median(), inplace= True)

C:\Users\Khaled\AppData\Local\Temp\ipykernel_8960\1747370998.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_employees_copy2['salary'].fillna(df_employees_copy2['salary'].median(), inplace= True)

In [2084]:
df_employees_copy2.isna().sum()

name          0
age           0
salary        0
department    0
dtype: int64

In [2085]:
info2 = {
    "name" : ["ali", "mohamed", "alaa", "samy"],
    "department": ["AI", np.nan, "AI", "Markting"]
}

df2 = pd.DataFrame(info2)
df2

      name department
0      ali         AI
1  mohamed        NaN
2     alaa         AI
3     samy   Markting

In [2086]:
df2['department'].fillna(df2['department'].mode()[0], inplace=True)

C:\Users\Khaled\AppData\Local\Temp\ipykernel_8960\2666989293.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['department'].fillna(df2['department'].mode()[0], inplace=True)

In [2087]:
df2

      name department
0      ali         AI
1  mohamed         AI
2     alaa         AI
3     samy   Markting

- **ffill() --> fill with the previous value**

In [2088]:
info3 = {
    "name" : ["ali", "mohamed", "alaa", "samy"],
    "department": ["Data science", np.nan, "AI", "Markting"]
}

df3 = pd.DataFrame(info3)
df3

      name    department
0      ali  Data science
1  mohamed           NaN
2     alaa            AI
3     samy      Markting

In [2089]:
df3['department'].ffill(inplace=True)

C:\Users\Khaled\AppData\Local\Temp\ipykernel_8960\2624287404.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df3['department'].ffill(inplace=True)

In [2090]:
df3

      name    department
0      ali  Data science
1  mohamed  Data science
2     alaa            AI
3     samy      Markting

#### `check duplication`

In [2091]:
df4 = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Ali", "Khaled", "Sara"],
    "Age": [23, 25, 23, "27", np.nan],
    "Salary": [15000, 18000, 15000, "20000", 22000],
    "Department": ["ML", "Data Science", "ML", " AI ", "AI"]
})

df4

     Name  Age Salary    Department
0     Ali   23  15000            ML
1   Ahmed   25  18000  Data Science
2     Ali   23  15000            ML
3  Khaled   27  20000           AI
4    Sara  NaN  22000            AI

In [2092]:
df4.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [2093]:
df4.duplicated().sum()

1

- *show duplicates*

In [2094]:
df4[df4.duplicated()]

  Name Age Salary Department
2  Ali  23  15000         ML

- **drop duplicates**

In [2095]:
df4.drop_duplicates(inplace=True)

### `Check data types`

In [2096]:
df5 = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Ali", "Khaled"],
    "Age": [23, 25, 23, "27"],
    "Salary": [15000, 18000, 15000, "20000"],
    "Department": ["ML", "Data Science", "ML", " AI "]
})

df5

     Name Age Salary    Department
0     Ali  23  15000            ML
1   Ahmed  25  18000  Data Science
2     Ali  23  15000            ML
3  Khaled  27  20000           AI

In [2097]:
df5.dtypes

Name          object
Age           object
Salary        object
Department    object
dtype: object

- **Convert a column to numeric**
    - *to_numeric()*

In [2098]:
df5["Salary"] = pd.to_numeric(df5["Salary"])

In [2099]:
df5["Salary"].dtype

dtype('int64')

In [2100]:
df5["Age"] = pd.to_numeric(df5["Age"])
df5['Age'].dtype

dtype('int64')

- What if there's bad data?

In [2101]:
df5["Age"] = ["23", "25", "unknown", "27"]

In [2102]:
df5['Age'].dtype

dtype('O')

In [2103]:
df5['Age'] = pd.to_numeric(df5['Age'] , errors='coerce')
df5['Age'].dtype

dtype('float64')

In [2104]:
df5['Age']

0    23.0
1    25.0
2     NaN
3    27.0
Name: Age, dtype: float64

##### `text cleaning`

In [2105]:
df5

     Name   Age  Salary    Department
0     Ali  23.0   15000            ML
1   Ahmed  25.0   18000  Data Science
2     Ali   NaN   15000            ML
3  Khaled  27.0   20000           AI

- *remove space and special characters*

- *strip('sep')*

In [2106]:
print(len(df5['Department'][3]))

4

In [2107]:
df5['Department'] = df5['Department'].str.strip()

In [2108]:
print(len(df5['Department'][3]))

2

- *lower()* || *upper()* || *capitalize()*

In [2109]:
df5['Department']

0              ML
1    Data Science
2              ML
3              AI
Name: Department, dtype: object

In [2110]:
df5["Department"] = df5["Department"].str.lower()
df5['Department']

0              ml
1    data science
2              ml
3              ai
Name: Department, dtype: object

In [2111]:
df5["Department"] = df5["Department"].str.upper()
df5['Department']

0              ML
1    DATA SCIENCE
2              ML
3              AI
Name: Department, dtype: object

In [2112]:
df5["Department"] = df5["Department"].str.capitalize()
df5['Department']

0              Ml
1    Data science
2              Ml
3              Ai
Name: Department, dtype: object

#### `sort_values() + value_counts() + Unique Values`

In [2113]:
df6 = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Khaled", "Sara", "Mona", "Omar"],
    "Age": [23, 25, 27, 22, 25, 27],
    "Department": ["ML", "AI", "ML", "Data Science", "AI", "ML"],
    "Salary": [15000, 18000, 22000, 16000, 20000, 25000]
})

df6

     Name  Age    Department  Salary
0     Ali   23            ML   15000
1   Ahmed   25            AI   18000
2  Khaled   27            ML   22000
3    Sara   22  Data Science   16000
4    Mona   25            AI   20000
5    Omar   27            ML   25000

In [2114]:
df6.sort_values("Salary", ascending=True, inplace=True)
df6

     Name  Age    Department  Salary
0     Ali   23            ML   15000
3    Sara   22  Data Science   16000
1   Ahmed   25            AI   18000
4    Mona   25            AI   20000
2  Khaled   27            ML   22000
5    Omar   27            ML   25000

In [2115]:
df6.sort_values("Salary", ascending=False, inplace=True)
df6

     Name  Age    Department  Salary
5    Omar   27            ML   25000
2  Khaled   27            ML   22000
4    Mona   25            AI   20000
1   Ahmed   25            AI   18000
3    Sara   22  Data Science   16000
0     Ali   23            ML   15000

In [2116]:
df6.sort_values(["Age","Salary"], ascending=[False, True], inplace=True)
df6

     Name  Age    Department  Salary
2  Khaled   27            ML   22000
5    Omar   27            ML   25000
1   Ahmed   25            AI   18000
4    Mona   25            AI   20000
0     Ali   23            ML   15000
3    Sara   22  Data Science   16000

- *show unique values only*

In [2117]:
df6['Department'].unique().tolist()

['ML', 'AI', 'Data Science']

- *total unique values*

In [2118]:
df6['Department'].nunique()

3

- *value_counts*

In [2119]:
df6['Department'].value_counts()

Department
ML              3
AI              2
Data Science    1
Name: count, dtype: int64

- *value_counts() + normalize*

In [2120]:
df6["Department"].value_counts(normalize=True)

Department
ML              0.500000
AI              0.333333
Data Science    0.166667
Name: proportion, dtype: float64

### `groupby()`

In [2121]:
df6.groupby("Department")

In [2122]:
df6.groupby("Department")["Salary"].mean()

Department
AI              19000.000000
Data Science    16000.000000
ML              20666.666667
Name: Salary, dtype: float64

In [2123]:
df6.groupby("Department")["Salary"].sum()

Department
AI              38000
Data Science    16000
ML              62000
Name: Salary, dtype: int64

In [2124]:
df6.groupby("Department")["Name"].count()

Department
AI              2
Data Science    1
ML              3
Name: Name, dtype: int64

- *agg()* || *aggregation()*

In [2125]:
df6.groupby("Department")["Salary"].agg(
    ["min", "max", "mean", "sum"]
)

                min    max          mean    sum
Department
AI            18000  20000  19000.000000  38000
Data Science  16000  16000  16000.000000  16000
ML            15000  25000  20666.666667  62000

In [2126]:
df6.groupby("Department").agg(
    {
        "Salary": ["mean", "min", "max"],
        "Age": ["mean", "min", "max"]
    })

                    Salary                      Age
                      mean    min    max       mean min max
Department
AI            19000.000000  18000  20000  25.000000  25  25
Data Science  16000.000000  16000  16000  22.000000  22  22
ML            20666.666667  15000  25000  25.666667  23  27

##### **`apply() + map() + lambda + .str`**

In [2127]:
df7 = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Khaled", "Sara"],
    "Age": [20, 25, 30, 22],
    "Salary": [15000, 18000, 25000, 16000]
})

df7

     Name  Age  Salary
0     Ali   20   15000
1   Ahmed   25   18000
2  Khaled   30   25000
3    Sara   22   16000

- *lambda & apply*

In [2128]:
df7['Age'].apply(lambda x : x + 1)

0    21
1    26
2    31
3    23
Name: Age, dtype: int64

In [2129]:
df7["Salary_Level"] = df7['Salary'].apply(lambda x : "High" if x >= 20000 else "Low")

In [2130]:
df7

     Name  Age  Salary Salary_Level
0     Ali   20   15000          Low
1   Ahmed   25   18000          Low
2  Khaled   30   25000         High
3    Sara   22   16000          Low

- *map()*

In [2131]:
df8 = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Khaled", "Sara"],
    "Department": ["ML", "AI", "DS", "ML"],
    "Age" : [25,30,22,23]
})
df8

     Name Department  Age
0     Ali         ML   25
1   Ahmed         AI   30
2  Khaled         DS   22
3    Sara         ML   23

In [2132]:
department_name = {
    "AI": "Artificial Intelligence",
    "ML": "Machine Learning",
    "DS": "Data Science"
}

df8['Department'] = df8['Department'].map(department_name)

In [2133]:
df8['Department']

0           Machine Learning
1    Artificial Intelligence
2               Data Science
3           Machine Learning
Name: Department, dtype: object

In [2134]:
df8['Age'] = df8['Age'].map(lambda x : x + 1)

In [2135]:
df8['Age']

0    26
1    31
2    23
3    24
Name: Age, dtype: int64

##### `map()` vs `apply()` in Pandas

| Feature         | `map()`                                     | `apply()`                               |
| --------------- | ------------------------------------------- | --------------------------------------- |
| Works mainly on | **Series**                                  | **Series & DataFrame**                  |
| Purpose         | Transform each value                        | Apply a function to values/rows/columns |
| Best for        | Dictionary mapping & simple transformations | Custom logic & more complex operations  |
| Input           | Usually a dictionary or function            | Usually a function                      |
| Example         | `df["Department"].map(mapping)`             | `df["Salary"].apply(lambda x: x * 1.1)` |

---

#### 1. `map()`

Use `map()` when you want to **replace or transform each value** based on a mapping.

##### Idea

```text
AI → Artificial Intelligence
ML → Machine Learning
DS → Data Science
```

---

#### 2. `apply()`

Use `apply()` when you want to **run a function** on each value, row, or column.

- *.str*

In [2136]:
df8['Name']

0       Ali
1     Ahmed
2    Khaled
3      Sara
Name: Name, dtype: object

In [2137]:
df8["Name"].str.upper()

0       ALI
1     AHMED
2    KHALED
3      SARA
Name: Name, dtype: object

In [2138]:
df8["Name"].str.lower()

0       ali
1     ahmed
2    khaled
3      sara
Name: Name, dtype: object

In [2139]:
df8["Name"].str.strip()

0       Ali
1     Ahmed
2    Khaled
3      Sara
Name: Name, dtype: object

In [2140]:
df8["Name"].str.len()

0    3
1    5
2    6
3    4
Name: Name, dtype: int64

In [2141]:
df8["Name"].str.contains("a")

0    False
1    False
2     True
3     True
Name: Name, dtype: bool

In [2142]:
df8[df8["Name"].str.contains("a")]

     Name        Department  Age
2  Khaled      Data Science   23
3    Sara  Machine Learning   24

In [2143]:
df8.loc[1, 'Department'] = "Artificial-Intelligence"
df8.loc[2, 'Department'] = "Data-Science"

In [2144]:
df8['Department']

0           Machine Learning
1    Artificial-Intelligence
2               Data-Science
3           Machine Learning
Name: Department, dtype: object

In [2145]:
df8["Department"].str.replace("-", " ")

0           Machine Learning
1    Artificial Intelligence
2               Data Science
3           Machine Learning
Name: Department, dtype: object

### `merge() + concat()`

In [2146]:
employees = pd.DataFrame({ 
    "EmployeeID": [1, 2, 3, 4, 5, 6], 
    "Name": ["Ali", "Ahmed", "Khaled", "Sara", "Omar", "Mona"], 
    "DepartmentID": [10, 20, 10, 30, 40, 50], 
    "Salary": [15000, 18000, 22000, 16000, 20000, 17000] 
    })
employees.head()

   EmployeeID    Name  DepartmentID  Salary
0           1     Ali            10   15000
1           2   Ahmed            20   18000
2           3  Khaled            10   22000
3           4    Sara            30   16000
4           5    Omar            40   20000

In [2147]:
departments = pd.DataFrame({ 
    "DepartmentID": [10, 20, 30, 60], 
    "DepartmentName": [ "Machine Learning", "Artificial Intelligence", "Data Science", "Cyber Security" ], 
    "Manager": ["Mohamed", "Hassan", "Youssef", "Mahmoud"] 
})
departments.head()

   DepartmentID           DepartmentName  Manager
0            10         Machine Learning  Mohamed
1            20  Artificial Intelligence   Hassan
2            30             Data Science  Youssef
3            60           Cyber Security  Mahmoud

- **merge**

In [2148]:
result = pd.merge(
    employees,
    departments,
    on="DepartmentID"
)

In [2149]:
result.head()

   EmployeeID    Name  DepartmentID  Salary           DepartmentName  Manager
0           1     Ali            10   15000         Machine Learning  Mohamed
1           2   Ahmed            20   18000  Artificial Intelligence   Hassan
2           3  Khaled            10   22000         Machine Learning  Mohamed
3           4    Sara            30   16000             Data Science  Youssef

- *how="left"*

In [2150]:
pd.merge(
    employees,
    departments,
    on="DepartmentID",
    how="left"
)

   EmployeeID    Name  DepartmentID  Salary           DepartmentName  Manager
0           1     Ali            10   15000         Machine Learning  Mohamed
1           2   Ahmed            20   18000  Artificial Intelligence   Hassan
2           3  Khaled            10   22000         Machine Learning  Mohamed
3           4    Sara            30   16000             Data Science  Youssef
4           5    Omar            40   20000                      NaN      NaN
5           6    Mona            50   17000                      NaN      NaN

- *how="right"*

In [2151]:
pd.merge(
    employees,
    departments,
    on="DepartmentID",
    how="right"
)

   EmployeeID    Name  DepartmentID   Salary           DepartmentName  Manager
0         1.0     Ali            10  15000.0         Machine Learning  Mohamed
1         3.0  Khaled            10  22000.0         Machine Learning  Mohamed
2         2.0   Ahmed            20  18000.0  Artificial Intelligence   Hassan
3         4.0    Sara            30  16000.0             Data Science  Youssef
4         NaN     NaN            60      NaN           Cyber Security  Mahmoud

- *how="outer"*

In [2152]:
pd.merge(
    employees,
    departments,
    on="DepartmentID",
    how="outer"
)

   EmployeeID    Name  DepartmentID   Salary           DepartmentName  Manager
0         1.0     Ali            10  15000.0         Machine Learning  Mohamed
1         3.0  Khaled            10  22000.0         Machine Learning  Mohamed
2         2.0   Ahmed            20  18000.0  Artificial Intelligence   Hassan
3         4.0    Sara            30  16000.0             Data Science  Youssef
4         5.0    Omar            40  20000.0                      NaN      NaN
5         6.0    Mona            50  17000.0                      NaN      NaN
6         NaN     NaN            60      NaN           Cyber Security  Mahmoud

- *how="inner"*

In [2153]:
pd.merge(
    employees,
    departments,
    on="DepartmentID",
    how="inner"
)

   EmployeeID    Name  DepartmentID  Salary           DepartmentName  Manager
0           1     Ali            10   15000         Machine Learning  Mohamed
1           2   Ahmed            20   18000  Artificial Intelligence   Hassan
2           3  Khaled            10   22000         Machine Learning  Mohamed
3           4    Sara            30   16000             Data Science  Youssef

- **concat()**

In [2154]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Ahmed"],
    "Age": [20, 25]
})

df2 = pd.DataFrame({
    "Name": ["Khaled", "Sara"],
    "Age": [30, 22]
})

- **Concatenate Rows**

In [2155]:
result = pd.concat([df1, df2], ignore_index=True)

In [2156]:
result.head()

     Name  Age
0     Ali   20
1   Ahmed   25
2  Khaled   30
3    Sara   22

- **Concatenate Columns**

In [2157]:
df1 = pd.DataFrame({
    "Name": ["Ali", "Ahmed"]
})

df2 = pd.DataFrame({
    "Salary": [15000, 18000]
})

In [2158]:
result = pd.concat(
    [df1, df2],
    axis=1,
    ignore_index=True
)
result.head()

       0      1
0    Ali  15000
1  Ahmed  18000

### `CSV + Excel + SQL + JSON`

- **from csv**

In [2159]:
path = os.path.join(os.getcwd(), "datasets/taxis.csv")

df_taxis = pd.read_csv(path)
df_taxis.head()

,pickup,dropoff,passengers,distance,fare,tip,tolls,total,color,payment,pickup_zone,dropoff_zone,pickup_borough,dropoff_borough
0,2019-03-23 20:21:09,2019-03-23 20:27:24,1,1.60,7.0,2.15,0.0,12.95,yellow,credit card,Lenox Hill West,UN/Turtle Bay South,Manhattan,Manhattan
1,2019-03-04 16:11:55,2019-03-04 16:19:00,1,0.79,5.0,0.00,0.0,9.30,yellow,cash,Upper West Side South,Upper West Side South,Manhattan,Manhattan
2,2019-03-27 17:53:01,2019-03-27 18:00:25,1,1.37,7.5,2.36,0.0,14.16,yellow,credit card,Alphabet City,West Village,Manhattan,Manhattan
3,2019-03-10 01:23:59,2019-03-10 01:49:51,1,7.70,27.0,6.15,0.0,36.95,yellow,credit card,Hudson Sq,Yorkville West,Manhattan,Manhattan
4,2019-03-30 13:27:42,2019-03-30 13:37:14,3,2.16,9.0,1.10,0.0,13.40,yellow,credit card,Midtown East,Yorkville West,Manhattan,Manhattan

- **from xlsx**

In [2160]:
path1 = os.path.join(os.getcwd(), "datasets/Netflix.xlsx")

df_Netflix = pd.read_excel(path1)
df_Netflix.head()

        Date      Open      High       Low     Close  Adj Close     Volume
0 2002-05-23  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
1 2002-05-24  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2 2002-05-28  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
3 2002-05-29  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
4 2002-05-30  1.107857  1.107857  1.071429  1.071429   1.071429   10154200

- **from json**

In [2161]:
path2 = os.path.join(os.getcwd(), "datasets/airports.json")

df_airports = pd.read_json(path2)
df_airports.head()

                                            airports
0  {'code': 'ATL', 'name': 'Hartsfield-Jackson At...
1  {'code': 'PEK', 'name': 'Beijing Capital Inter...
2  {'code': 'DXB', 'name': 'Dubai International',...
3  {'code': 'LAX', 'name': 'Los Angeles Internati...
4  {'code': 'HND', 'name': 'Tokyo Haneda', 'city'...

- **from sql**

In [2162]:
pyodbc.drivers()

['SQL Server',
 'SQL Server Native Client 11.0',
 'ODBC Driver 13 for SQL Server',
 'ODBC Driver 17 for SQL Server']

In [2163]:
connection_string = quote_plus(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=NASR-ESH-PC01\\MSSQLSERVER2022;"
    "DATABASE=CompaneyDB;"
    "UID=sa;"
    "PWD=123@123qwe;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(
    f"mssql+pyodbc:///?odbc_connect={connection_string}"
)

df_emp = pd.read_sql(
    "SELECT * FROM [dbo].[Employees]",
    engine
)

df_emp

,EmployeeID,FirstName,LastName,Email,Age,Salary,HireDate,DepartmentID,managerid
0,1,Ahmed,Ali,ahmed@company.com,28,18000.0,2022-01-15,1,None
1,2,Mona,Hassan,mona@company.com,32,25000.0,2021-06-10,2,None
2,3,Omar,Khaled,omar@company.com,26,15000.0,2023-03-20,1,None
3,4,Sara,Mahmoud,sara@company.com,30,22000.0,2022-11-05,3,None
4,5,Youssef,Samir,youssef@company.com,24,12000.0,2024-01-12,5,None
5,6,Nour,Tarek,nour@company.com,27,17000.0,2023-07-01,4,None
6,7,Karim,Adel,karim@company.com,35,30000.0,2020-02-20,1,None
7,8,Hana,Mostafa,hana@company.com,29,19500.0,2022-09-12,5,None
8,9,Amr,Said,amr@company.com,31,21000.0,2021-12-01,3,None
9,10,Laila,Omar,laila@company.com,25,13000.0,2024-04-15,2,None
10,11,Tamer,Fathy,tamer@company.com,38,35000.0,2019-08-01,1,None
11,12,Dina,Ashraf,dina@company.com,23,11000.0,2025-01-10,5,None

- *to_csv()* & *to_excel()*

In [2164]:
df_emp.to_csv("output/employee.csv", index=False)
df_emp.to_excel("output/employee.xlsx", index=False)

### `Datetime`

- *to_datetime()*

In [2165]:
df9 = pd.DataFrame({
    "Name": ["Ali", "Ahmed", "Khaled", "Sara"],
    "JoinDate": [
        "2024-01-15",
        "2023-06-20",
        "2025-03-10",
        "2024-11-05"
    ]
})

df9

     Name    JoinDate
0     Ali  2024-01-15
1   Ahmed  2023-06-20
2  Khaled  2025-03-10
3    Sara  2024-11-05

In [2166]:
df9.dtypes

Name        object
JoinDate    object
dtype: object

In [2167]:
df9['JoinDate'] = pd.to_datetime(df9['JoinDate'])

In [2168]:
df9.dtypes

Name                object
JoinDate    datetime64[ns]
dtype: object

- get *Year*, *Month*, *Day*

In [2169]:
print(df9['JoinDate'].dt.year)
print(df9['JoinDate'].dt.month)
print(df9['JoinDate'].dt.day)

0    2024
1    2023
2    2025
3    2024
Name: JoinDate, dtype: int32
0     1
1     6
2     3
3    11
Name: JoinDate, dtype: int32
0    15
1    20
2    10
3     5
Name: JoinDate, dtype: int32

- *day_name*, *month_name*

In [2170]:
df9["JoinDate"].dt.day_name()

0     Monday
1    Tuesday
2     Monday
3    Tuesday
Name: JoinDate, dtype: object

In [2171]:
df9["JoinDate"].dt.month_name()

0     January
1        June
2       March
3    November
Name: JoinDate, dtype: object

### `Filtering date`

In [2172]:
df9[df9["JoinDate"] > "2024-01-01"]

     Name   JoinDate
0     Ali 2024-01-15
2  Khaled 2025-03-10
3    Sara 2024-11-05

In [2173]:
df9[
    (df9["JoinDate"] >= "2024-01-01") &
    (df9["JoinDate"] <= "2024-12-31")
]

   Name   JoinDate
0   Ali 2024-01-15
3  Sara 2024-11-05

In [2174]:
df9[
    df9["JoinDate"].between(
        "2024-01-01",
        "2024-12-31"
    )
]

   Name   JoinDate
0   Ali 2024-01-15
3  Sara 2024-11-05

#### `extract year, month, day` in separated column

In [2175]:
df9

     Name   JoinDate
0     Ali 2024-01-15
1   Ahmed 2023-06-20
2  Khaled 2025-03-10
3    Sara 2024-11-05

In [2176]:
df9["Year"] = df9["JoinDate"].dt.year
df9["Month"] = df9["JoinDate"].dt.month
df9["Day"] = df9["JoinDate"].dt.day

In [2177]:
df9

     Name   JoinDate  Year  Month  Day
0     Ali 2024-01-15  2024      1   15
1   Ahmed 2023-06-20  2023      6   20
2  Khaled 2025-03-10  2025      3   10
3    Sara 2024-11-05  2024     11    5

In [2179]:
pd.Timestamp.now()

Timestamp('2026-09-16 14:16:29.430157')

In [2180]:
pd.Timestamp.now().date()

datetime.date(2026, 9, 16)

In [2183]:
pd.Timestamp.now().normalize()

Timestamp('2026-09-16 00:00:00')

In [2181]:
df9['From_Join_till_Now'] = (
    pd.Timestamp.now().normalize() - pd.to_datetime(df9['JoinDate'])
).dt.days

In [2182]:
df9

     Name   JoinDate  Year  Month  Day  From_Join_till_Now
0     Ali 2024-01-15  2024      1   15                 975
1   Ahmed 2023-06-20  2023      6   20                1184
2  Khaled 2025-03-10  2025      3   10                 555
3    Sara 2024-11-05  2024     11    5                 680

In [2184]:
df9.sort_values('JoinDate')

     Name   JoinDate  Year  Month  Day  From_Join_till_Now
1   Ahmed 2023-06-20  2023      6   20                1184
0     Ali 2024-01-15  2024      1   15                 975
3    Sara 2024-11-05  2024     11    5                 680
2  Khaled 2025-03-10  2025      3   10                 555

### `Pivot Table`: is another way to summarize the data

In [ ]:
# pd.pivot_table(
#     df,
#     values="COLUMN_TO_CALCULATE",
#     index="ROWS",
#     columns="COLUMNS",
#     aggfunc="FUNCTION"
# )

In [2189]:
students = {
    "Name" : ["Ali", "Mohammed", "Omar", "Khaled", "Ali"],
    "Subject" : ["Physics", "Physics", "Physics", "Physics", "Chemistry"],
    "Sem1" : [88,92,78,60,61],
    "Sem2" : [91,95,81,63,64]
}

df_students = pd.DataFrame(students)
df_students.head()

       Name    Subject  Sem1  Sem2
0       Ali    Physics    88    91
1  Mohammed    Physics    92    95
2      Omar    Physics    78    81
3    Khaled    Physics    60    63
4       Ali  Chemistry    61    64

In [2191]:
df_students.pivot_table(index="Subject", columns="Name",values="Sem1")

Name        Ali  Khaled  Mohammed  Omar
Subject
Chemistry  61.0     NaN       NaN   NaN
Physics    88.0    60.0      92.0  78.0

In [2196]:
df_students.pivot_table(
    index="Subject",
    # columns="Name",
    values="Sem1",
    aggfunc=["mean", "std"]
)

           mean        std
           Sem1       Sem1
Subject
Chemistry  61.0        NaN
Physics    79.5  14.271183

- *if there's a null value*

In [2199]:
df_students.pivot_table(
    index="Subject",
    columns="Name",
    values="Sem1",
    aggfunc="mean",
    fill_value=200,
    margins=True,
    margins_name="Average"
)

Name        Ali  Khaled  Mohammed   Omar  Average
Subject
Chemistry  61.0   200.0     200.0  200.0     61.0
Physics    88.0    60.0      92.0   78.0     79.5
Average    74.5    60.0      92.0   78.0     75.8